[tool.poetry]
name = "{{ cookiecutter.project_slug }}"
version = "0.1.0"
description = "{{ cookiecutter.project_short_description }}"
authors = ["{{ cookiecutter.full_name }} <{{ cookiecutter.email }}>"]
license = "Proprietary"
packages = [
    { include = "{{ cookiecutter.module_name }}", from = "src" },
]
include = ["src/{{ cookiecutter.module_name }}/res/*"]
{% if cookiecutter.create_cli == "yes" %}
[tool.poetry.scripts]
{{ cookiecutter.project_slug }} = "{{ cookiecutter.module_name }}.main:app"
{% endif %}
[tool.poetry.dependencies]
python = "^3.10"{% if cookiecutter.config_file == 'hocon' %}
pyhocon = "^0.3.59"{% elif cookiecutter.config_file == 'yaml' %}
PyYAML = "^6.0"{% endif %}{% if cookiecutter.create_cli == 'yes' %}
typer = "^0.6.1"{% endif %}
importlib-metadata = {version = "^1.0", python = "<3.8"}

[tool.poetry.dev-dependencies]{% if cookiecutter.code_formatter == 'black' %}
black = "^22.8.0"{% endif %}
pre-commit = "^2.20.0"
pytest = "^7.1.3"
pytest-cov = "^4.0.0"{% if cookiecutter.use_notebooks == 'yes' %}
jupyterlab = "^3.4.7"{% endif %}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
